name: Reusable Workflow

on:
  workflow_call:
    inputs:
      name:
        description: "Name"
        required: true
        type: string

jobs:
  print-name:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Print name
        id: print-name
        run: |
          echo "Name: ${{ inputs.nema }}"

  print-secret:
    runs-on: ubuntu-latest
    needs: print
    steps:
      - name: Print secret
        id: print-secret
        run: |
          echo "Secret: ${{ toJSON(secrets) }}"
