name: Github Trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        required: true
        type: string

      gender:
        description: "Gender"
        required: true
        type: choice
        options:
          - male
          - female
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        id: print-name
        run: echo "Hello ${{ inputs.name }}"

      - name: Print gender
        id: print-gender
        run: echo "Hello ${{ inputs.gender }}"
