name: Github Trigger

run-name: ${{ inputs.name }} trigger workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        required: true
        type: string

      gender:
        description: "Gender"
        required: true
        type: choice
        options:
          - male
          - female
jobs:
  print:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: ${{ inputs.name }}

  composite:
    uses: nguyenvantruong9902/composite-actions
    with:
      name: ${{ inputs.name }}
