name: Github Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, $First_Name $Last_Name!
        env:
          First_Name: John
          Last_Name: Doe

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  start:
    runs-on: ubuntu-latest

    needs: welcome

    steps:
      - uses: actions/checkout@v4

      - name: The first step
        run: |
          echo "It's created by ${{ github.actor }}"
          echo "All secrets are available: ${{ toJson(secrets) }}"

  comment:
    runs-on: ubuntu-latest

    needs: start

    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Add comment to PR
        env:
          PR: ${{ github.event.pull_request.number }}
          run: |
            gh pr comment $PR --body "This is a comment"
