name: Github Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        id: one-line-script
        run: echo Hello, $First_Name $Last_Name!
        env:
          First_Name: John
          Last_Name: Doe

      - name: Run a multi-line script
        id: multi-line-script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  start:
    runs-on: ubuntu-latest
    needs: welcome
    if: github.event_name == 'pull_request' # Optional: restrict to PRs

    steps:
      - uses: actions/checkout@v4

      - name: The first step
        id: first-step
        run: |
          echo "It's created by ${{ github.actor }}"
          echo "All secrets are available: ${{ toJson(secrets) }}"

  comment:
    runs-on: ubuntu-latest
    needs: start
    if: github.event_name == 'pull_request_target'

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Add comment to PR
        id: add-comment
        if: ${{ vars.MESSAGE != '' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ vars.MESSAGE }}
