name: Github Workflow

on:
  label:
    types: [created]
  push:
    branches:
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, $First_Name $Last_Name!
        env:
          First_Name: John
          Last_Name: Doe

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  start:
    runs-on: ubuntu-latest

    needs: welcome

    steps:
      - uses: actions/checkout@v4

      - name: The first step
        run: echo It's created by ${{ github.actor }}
